#!/bin/dash
# Example for $XDG_CONFIG_HOME/sxiv/exec/image-info
# Called by sxiv(1) whenever an image gets loaded.
# The output is displayed in sxiv's status bar.
# Arguments:
#   $1: path to image file
#   $2: image width
#   $3: image height

R=$(realpath "$1")
exec 2>/dev/null
echo $PPID$(tmsu tags -- "$R"|cut -d : -f 2-)
