#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) whenever an unbound key combo is used,
# The next key combo is passed as its first argument. The paths of all marked
# images--or of the current image, if no image is marked--are passed via stdin,
# one file path per line.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.
# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

readonly KEY="$1";
readonly TMPFILE="/tmp/sxiv.$$"

rotate() {
	degree="$1"
	while read file; do
		case "$(file -b -i "$file")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
		*)           mogrify  -rotate "$degree" "$file" ;;
		esac
	done
}


case "$KEY" in
"C-c")      tr '\n' ' ' | xsel -i ;;
"C-g")      tr '\n' '\0' | xargs -0 gimp & ;;
"C-comma")  rotate 270 ;;
"C-period") rotate  90 ;;
"C-slash")  rotate 180 ;;
esac

